onlineSchool/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path, include

from core import views
from onlineSchool import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('__debug__/', include('debug_toolbar.urls')),
    path('summernote/', include('django_summernote.urls')),
    path('__debug__/', include('debug_toolbar.urls')),
    path('registration/', views.RegistrationView.as_view()),
    path('login/', LoginView.as_view(template_name='login.html')),
    path('logout/', LogoutView.as_view()),
    path('profile/', views.ProfileView.as_view()),
    path('', views.IndexView.as_view()),
    path('courses', views.CourseByCategoryView.as_view()),
    path('course/<int:pk>/', views.CourseView.as_view()),
    path('homework/<int:pk_homework>/eval/', views.EvaluateHomeworkView.as_view()),
    path('course/<int:pk>/lecture/<int:pk_lecture>/', views.LectureView.as_view()),
    path('course/<int:pk>/lecture/<int:pk_lecture>/done/', views.LectureView.as_view()),
    path('course/<int:pk>/add-comment/', views.AddCommentView.as_view()),
    path('course/<int:pk>/students/', views.StudentsView.as_view()),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/models.py
import datetime
from django.contrib.auth.models import AbstractUser
from django.db import models


def avatar_upload_to(obj, filename):
    return f"avatars/{filename}"


def poster_upload_to(obj, filename):
    return f"posters/{filename}"


class Student(AbstractUser):
    role = models.ForeignKey('Role', on_delete=models.CASCADE)
    course = models.ManyToManyField('Course', related_name='student_course', blank=True)
    avatar = models.ImageField(blank=True, upload_to=avatar_upload_to, default='avatar/default.png')
    lecture_finished = models.ManyToManyField('Lecture', related_name='lecture_finished', blank=True)
    course_finished = models.ManyToManyField('Course', related_name='course_finished', blank=True)

    def __str__(self):
        return self.username


class Role(models.Model):
    title = models.CharField(max_length=20)

    def __str__(self):
        return self.title


class Category(models.Model):
    title = models.CharField(max_length=50)
    is_enabled = models.BooleanField()

    def __str__(self):
        return self.title


class Course(models.Model):
    title = models.CharField(max_length=50)
    description = models.TextField()
    price = models.IntegerField()
    is_enabled = models.BooleanField()
    category = models.ForeignKey('Category', on_delete=models.SET_NULL, null=True, blank=True)
    date_end = models.DateTimeField()
    photo = models.ImageField(blank=True, upload_to=poster_upload_to, default='posters/default.png')

    def __str__(self):
        return self.title


class Lecture(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField()
    video = models.CharField(max_length=255)
    photo = models.ImageField(blank=True, null=True, upload_to=poster_upload_to)
    course = models.ForeignKey('Course', on_delete=models.CASCADE)

    def __str__(self):
        return self.title


class Comment(models.Model):
    user = models.ForeignKey('Student', on_delete=models.CASCADE)
    course = models.ForeignKey('Course', on_delete=models.CASCADE)
    message = models.TextField()
    is_approved = models.BooleanField()

    def __str__(self):
        return f"{self.user.username} -> {self.course.title}"


class Homework(models.Model):
    lecture = models.ForeignKey('lecture', on_delete=models.CASCADE)
    description = models.TextField()

    def __str__(self):
        return self.description


class HomeworkStudentDone(models.Model):
    user = models.ForeignKey('Student', on_delete=models.CASCADE)
    user_homework = models.TextField()
    homework = models.ForeignKey('Homework', on_delete=models.CASCADE)
    mark = models.IntegerField(default=0)

    def __str__(self):
        return f"{self.user.username} -> {self.homework.lecture.title}"


class Subscription(models.Model):
    user = models.ForeignKey('Student', on_delete=models.CASCADE)
    course = models.ForeignKey('Course', on_delete=models.CASCADE)
    payment_id = models.CharField(max_length=255)
    payment_message = models.CharField(max_length=255)
    payment_status = models.CharField(max_length=255)
    date = models.IntegerField()

    def __str__(self):
        return f"{self.user.username} -> {datetime.datetime.utcfromtimestamp(self.date).ctime()}"


models = [Role, Category, Comment, HomeworkStudentDone]
summer_models = [Homework, Course, Lecture]

core/forms.py
from django import forms
from django.contrib.auth import get_user_model


class RegistrationForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control mb-3'}))
    check_password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control mb-3'}))


    class Meta:
        model = get_user_model()
        fields = (
            'first_name',
            'last_name',
            'username',
            'email',
            'avatar',
            'role'
        )
        widgets = {
            'first_name' : forms.widgets.TextInput(attrs={'class': 'form-control mb-3'}),
            'last_name' : forms.widgets.TextInput(attrs={'class': 'form-control mb-3'}),
            'username' : forms.widgets.TextInput(attrs={'class': 'form-control mb-3'}),
            'email' : forms.widgets.EmailInput(attrs={'class': 'form-control mb-3'}),
            'avatar' : forms.widgets.FileInput(attrs={'class': 'form-control mb-3'}),
            'role' : forms.widgets.Select(attrs={'class': 'form-select mb-3'})
        }
    def clean_check_password(self):
        if self.cleaned_data['password'] != self.cleaned_data['check_password']:
            raise forms.ValidationError('Passwords do not match')
        return self.cleaned_data['check_password']

    def save(self, commit=True):
        user = super().save(commit=True)
        user.set_password(self.cleaned_data['password'])
        user.save()
        return user

core/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Count
from django.shortcuts import render, redirect
from django.views.generic import FormView, ListView, DetailView, TemplateView
from core.forms import RegistrationForm
from core.models import Course, Category, Lecture, Comment, Homework, HomeworkStudentDone


class RegistrationView(FormView):
    template_name = 'registration.html'
    form_class = RegistrationForm
    success_url = '/login/'

    def form_valid(self, form):
        form.save()
        return super().form_valid(form)


class ProfileView(LoginRequiredMixin, ListView):
    template_name = 'profile.html'
    model = get_user_model()


class IndexView(LoginRequiredMixin, ListView):
    template_name = 'index.html'
    model = Course
    paginate_by = 6

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        categories = Category.objects.all()
        context.update({
            'categories': categories
        })
        return context

    def get_queryset(self):
        if self.request.user.role.title == 'Teacher':
            return Course.objects.filter(student_course=self.request.user.id)
        else:
            courses = Course.objects.all().annotate(
                count=Count('student_course')
            ).order_by('-count')
            return courses


class CourseByCategoryView(LoginRequiredMixin, ListView):
    template_name = 'includes/courses.html'
    model = Course
    paginate_by = 6

    def get_queryset(self):
        return Course.objects.filter(category_id=self.request.GET.get('category')).annotate(
            count=Count('student_course')
        ).order_by('-count')


class CourseView(LoginRequiredMixin, DetailView):
    template_name = 'course.detail.html'
    model = Course

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        courses = Course.objects.filter(student_course__username=self.request.user)
        if Course.objects.get(title__contains=kwargs.get('object')) in courses:
            lectures = Lecture.objects.filter(course_id=kwargs.get('object'))
            context['lectures'] = lectures
            comments = Comment.objects.filter(course_id=kwargs.get('object'))
            context['comments'] = comments
        else:
            pass
        return context


class AddCommentView(LoginRequiredMixin, TemplateView):
    template_name = 'includes/comments.html'

    def post(self, request, *args, **kwargs):
        Comment.objects.create(
            message=request.POST.get('comment'),
            course_id=kwargs.get('pk'),
            user_id=request.user.id,
            is_approved=True
        )
        return redirect(request.META['HTTP_REFERER'])


class StudentsView(LoginRequiredMixin, ListView):
    template_name = 'students.html'
    get_user_model()

    def get_queryset(self):
        return get_user_model().objects.filter(course=self.kwargs.get('pk'))


class LectureView(LoginRequiredMixin, DetailView):
    template_name = 'lecture_detail.html'
    model = Lecture
    pk_url_kwarg = 'pk_lecture'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        homeworks = Homework.objects.filter(lecture_id=kwargs.get('object').id)
        context.update({
            'homeworks': homeworks
        })
        return context

    def post(self, request, *args, **kwargs):
        current_lecture = Lecture.objects.get(id=kwargs.get('pk_lecture'))
        if current_lecture in request.user.lecture_finished.all():
            request.user.lecture_finished.remove(
                kwargs.get('pk_lecture')
            )
        else:
            request.user.lecture_finished.add(
                kwargs.get('pk_lecture')
            )

        return redirect(request.META['HTTP_REFERER'])


class EvaluateHomeworkView(LoginRequiredMixin, TemplateView):
    template_name = 'lecture_detail.html'

    def post(self, request, *args, **kwargs):
        homework = HomeworkStudentDone.objects.get(id=kwargs.get('pk_homework'))
        mark = request.POST.get('mark')
        homework.mark = mark
        homework.save()

        return redirect(request.META['HTTP_REFERER'])

core/templates/base.html
{% load static %}

<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.3.0/css/all.min.css">
    <title>Online School</title>
    {% block css %} {% endblock %}
</head>
<body>
<header class="p-3 mb-3 border-bottom">
    <div class="container">
        <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
            <a href="/" class="d-flex align-items-center mb-2 mb-lg-0 text-dark text-decoration-none">

            </a>

            <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
                <li><a href="/" class="nav-link px-2 link-dark">Home</a></li>
                <li><a href="#" class="nav-link px-2 link-dark">Link 3</a></li>
                <li><a href="#" class="nav-link px-2 link-dark">Link 4</a></li>
            </ul>

            <form class="col-12 col-lg-auto mb-3 mb-lg-0 me-lg-3" role="search">
                <input type="search" class="form-control" placeholder="Search..." aria-label="Search">
            </form>

            <div class="dropdown text-end">
                <a href="#" class="d-block link-dark text-decoration-none dropdown-toggle" data-bs-toggle="dropdown"
                   aria-expanded="false">
                    <img width="48" height="48" class="rounded-circle"
                         {% if user.avatar %}
                            src="{{ user.avatar.url }}"
                         {% else %}
                            src="{% static 'img/default.png' %}"
                         {% endif %}
                    >
                </a>
                <ul class="dropdown-menu text-small">
                    <li class="dropdown-item">{{ user.username }}</li>
                    {% if user.is_superuser %}
                    <li><a class="dropdown-item" href="/admin">Admin panel</a></li>
                    {% endif %}
                    <li><a class="dropdown-item" href="/profile">Profile</a></li>
                    <li>
                        <hr class="dropdown-divider">
                    </li>
                    <li><a class="dropdown-item" href="/logout">Sign out</a></li>
                </ul>
            </div>
        </div>
    </div>
</header>


{% block content %} {% endblock %}
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN"
        crossorigin="anonymous"></script>
{% block js %} {% endblock %}
</body>
</html>

core/templates/course.detail.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <div class="card mb-3">
        <img {% if object.photo %}
             src="{{ object.photo.url }}"
             {% else %}
             src="http://via.placeholder.com/400x100"
             {% endif %}
             width="400px" height="100px" class="card-img-top" alt="poster"
        >
        <div class="card-body">
            <div class="d-flex justify-content-between">
                <h5 class="card-title">{{ object.title }}</h5>
                {% if course in user.course.all %}
                    <a href="students/" class="btn btn-primary">Student</a>
                {% endif %}
            </div>

            <p class="card-text text-muted">{{ object.category }}</p>
            <p class="card-text text-muted">{{ object.date_end }}</p>
            <p class="card-text">{{ object.description|safe }}</p>

            {% if lectures %}
            <ul class="list-group list-group-flush">
                {% for lecture in lectures %}
                <li class="list-group-item">
                    <div class="card">
                        <div class="card-header">
                            <h5 class="card-title">{{ lecture.title }}</h5>
                        </div>
                        <div class="card-body">
                            <img {% if lecture.photo %}
                                 src="{{ lecture.photo.url }}"
                                 {% else %}
                                 src="http://via.placeholder.com/400x100"
                                 {% endif %}
                                 width="200px" height="100px" class="card-img-top" alt="poster"
                            >
                            <p class="card-text">{{ lecture.description|safe|truncatewords:10 }}</p>
                        </div>
                        <div class="card-footer">
                            <a href="lecture/{{ lecture.id }}" class="btn btn-primary">View more</a>
                        </div>
                    </div>
                </li>
                {% endfor %}
            </ul>
            {% endif %}
        </div>
            {% if course in user.course.all %}
                <div class="card-footer">
                    <h3>Comments</h3>
                    {% if comments %}
                        {% include 'includes/comments.html' %}
                    {% endif %}
                    <form action="add-comment/" method="POST">{% csrf_token %}
                        <label for="comment" class="mb-2">Comment</label>
                        <textarea name="comment" class="form-control mb-3" required id="comment"></textarea>
                        <button class="btn btn-outline-primary" type="submit">Send</button>
                    </form>
                </div>
            {% else %}
                <h3 class="m-3 text-warning">You not subscribe at this course</h3>
            {% endif %}
    </div>
</div>
{% endblock %}

core/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="container">
    {% if categories %}
    <div class="row justify-content-end">
        <div class="col-1">
            <label for="categorySelect">Filter by</label>
            <select name="category" id="categorySelect" class="form-select mb-3">
                {% for category in categories %}
                {% if category.is_enabled %}
                <option value="{{ category.id }}">{{ category.title }}</option>
                {% endif %}
                {% endfor %}
            </select>
        </div>
    </div>
    {% endif %}

    <div class="row gy-4" id="courses">
        {% include 'includes/courses.html' %}
    </div>

    <div class="d-flex flex-column align-items-center mt-5">
            <span class="current">
                Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
            </span>

        <ul class="pagination">
            <li class="page-item">
                <a href="?page=1" class="page-link">&laquo; first</a>
            </li>
            <li class="page-item">
                <a
                        {% if page_obj.has_previous %}
                        href="?page={{ page_obj.previous_page_number }}"
                        {% else %}
                        disabled
                        {% endif %} class="page-link">Previous</a>
            </li>
            {% for page in paginator.page_range %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page }}">{{ page }}</a>
            </li>
            {% endfor %}

            <li class="page-item">
                <a
                        {% if page_obj.has_next %}
                        href="?page={{ page_obj.next_page_number }}"
                        {% else %}
                        disabled
                        {% endif %} class="page-link">Next</a>
            </li>
            <li class="page-item">
                <a href="?page={{ page_obj.paginator.num_pages }}" class="page-link">last &raquo;</a>
            </li>
        </ul>
    </div>
</div>
{% endblock %}

{% block js %}
    <script src="{% static 'js/script.js' %}"></script>
{% endblock %}

core/templates/lecture_detail.html
{% extends 'base.html' %}
{% load core_tags %}
{% load static %}

{% block content %}
<biv class="container">
    <div class="card">
        <div class="card-header d-flex justify-content-between align-item-center py-3">
            <h2>{{ lecture.title }}</h2>

            <form action="done/" method="post">{% csrf_token %}
                {% if request.user in lecture.lecture_finished.all %}
                <button type="submit" class="btn btn-warning">Unfinished</button>
                {% else %}
                <button type="submit" class="btn btn-primary">Finish</button>
                {% endif %}
            </form>
        </div>

        <div class="card-body d-flex flex-column">
            <p>{{ lecture.description|safe }}</p>
            <iframe class="align-self-center" width="1200" height="400"
                    src="https://www.youtube.com/embed/{{ lecture.video|get_code }}"
                    title="YouTube video player" frameborder="0"
                    allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"
                    allowfullscreen></iframe>
        </div>

        {% if homeworks %}
        <div class="card-footer">
            <h3>Homeworks</h3>
            {% for homework in homeworks %}
            <div class="border my-3 p-3">
                <h4>{{ homework.description|safe }}</h4>

                {% if request.user.role.title == 'Student' %}
                {% for homework1 in homework.homeworkstudentdone_set.all %}

                {% if homework1.mark %}
                <mark class="fs-4">{{ homework1.mark }}</mark>
                {% endif %}
                {% endfor %}
                <form action="homework/{{ homework.id }}/pass" method="post" class="input-group">{% csrf_token %}
                    <input type="text" name="homework" placeholder="Link on your repository" class="form-control">
                    <button class="btn btn-outline-success" type="submit">Pass</button>
                </form>
                {% else %}
                <ul class="list-group">
                    {% for homework1 in homework.homeworkstudentdone_set.all %}
                    <li class="list-group-item fs-4">
                        {{ homework1 }} -> {{ homework1.user_homework }}
                        <form action="/homework/{{ homework1.id }}/eval/" method="post">{% csrf_token %}
                            <input type="range" name="mark" class="form-range" min="10" max="100"
                                   id="{{ homework1.id }}" width="60%">
                            <p id="{{ homework1.id }}-value" class="text-center fs-3"></p>
                            <div class="col d-flex justify-content-center">
                                <button class="btn btn-primary" type="submit">Evaluate</button>
                            </div>

                        </form>
                    </li>
                    {% endfor %}
                </ul>
                {% endif %}
            </div>
            {% endfor %}
        </div>
        {% endif %}
    </div>
</biv>
{% endblock %}

{% block js %}

<script
        src="https://code.jquery.com/jquery-3.6.0.min.js"
        integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4="
        crossorigin="anonymous"></script>
<script src="{% static 'js/lecture_script.js' %}"></script>
{% endblock %}

core/templates/login.html
{% load bootstrap4 %}

<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <title>Login</title>
</head>
<body>
<!-- Section: Design Block -->
<section class="text-center text-lg-start">
    <style>
    .cascading-right {
      margin-right: -50px;
    }

    @media (max-width: 991.98px) {
      .cascading-right {
        margin-right: 0;
      }
    }

    </style>

    <!-- Jumbotron -->
    <div class="container py-4">
        <div class="row g-0 align-items-center">
            <div class="col-lg-6 mb-5 mb-lg-0">
                <div class="card cascading-right" style="
            background: hsla(0, 0%, 100%, 0.55);
            backdrop-filter: blur(30px);
            ">
                    <div class="card-body p-5 shadow-5 text-center">
                        <h2 class="fw-bold mb-5">Sign in or <a href="/registration" class="text-decoration-none">Register</a></h2>
                        <form class="col-8 mx-auto" method="post"> {% csrf_token %}
                             {% bootstrap_form form %}

                            <!-- Submit button -->
                            <button type="submit" class="btn btn-primary btn-block my-4">
                                Sign in
                            </button>

                            <!-- Register buttons -->
                            <div class="text-center">
                                <p>or sign up with:</p>
                                <button type="button" class="btn btn-link btn-floating mx-1">
                                    <i class="fab fa-facebook-f"></i>
                                </button>

                                <button type="button" class="btn btn-link btn-floating mx-1">
                                    <i class="fab fa-google"></i>
                                </button>

                                <button type="button" class="btn btn-link btn-floating mx-1">
                                    <i class="fab fa-twitter"></i>
                                </button>

                                <button type="button" class="btn btn-link btn-floating mx-1">
                                    <i class="fab fa-github"></i>
                                </button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>

            <div class="col-lg-6 mb-5 mb-lg-0">
                <img src="https://mdbootstrap.com/img/new/ecommerce/vertical/004.jpg" class="w-100 rounded-4 shadow-4"
                     alt=""/>
            </div>
        </div>
    </div>
    <!-- Jumbotron -->
</section>
<!-- Section: Design Block -->

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN"
        crossorigin="anonymous"></script>
</body>
</html>

core/templates/profile.html
{% extends 'base.html' %}
{% load static %}
{% load core_tags %}

{% block content %}
<section style="background-color: #eee;">
    <div class="container py-5">
        <div class="row">
            <div class="col-lg-4">
                <div class="card mb-4">
                    <div class="card-body text-center">
                        <img style="width: 100px; height: 100px"
                             {% if user.avatar %}
                             src="{{ user.avatar.url }}"
                             {% endif %}
                             class="rounded-circle mb-3" alt="..."
                        >
                        <h5 class="my-3">{{ user.first_name }} {{ user.last_name }}</h5>
                        <p class="text-muted mb-1">{{ user.role }}</p>
                    </div>
                </div>
                <div class="card mb-4 mb-lg-0">
                    <h5 class="px-3 pt-3">Completed Course</h5>
                    <div class="card-body p-0">
                        <ul class="list-group list-group-flush rounded-3">
                            {% for completed_course in user.course_finished.all %}
                            <li class="list-group-item d-flex justify-content-between align-items-center p-3">
                                {{ completed_course }} -> {{ completed_course|avg|floatformat:2 }}%
                            </li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>
            </div>
            <div class="col-lg-8">
                <div class="card mb-4">
                    <div class="card-body">
                        <div class="row">
                            <div class="col-sm-3">
                                <p class="mb-0">Full Name</p>
                            </div>
                            <div class="col-sm-9">
                                <p class="text-muted mb-0">{{ user.first_name }} {{ user.last_name }}</p>
                            </div>
                        </div>
                        <hr>
                        <div class="row">
                            <div class="col-sm-3">
                                <p class="mb-0">Email</p>
                            </div>
                            <div class="col-sm-9">
                                <p class="text-muted mb-0">{{ user.email }}</p>
                            </div>
                        </div>
                        <hr>
                        <div class="row">
                            <div class="col-sm-3">
                                <p class="mb-0">Username</p>
                            </div>
                            <div class="col-sm-9">
                                <p class="text-muted mb-0">{{ user.username }}</p>
                            </div>
                        </div>
                    </div>
                    <a class="btn btn-primary" href="{{ request.path }}{{ user.id }}/edit">Edit</a>
                </div>
                <div class="row">
                    <div class="col-md-12">
                        <div class="card mb-4 mb-md-0">
                            <div class="card-body">
                                <p class="mb-4">
                                    Course Status
                                </p>
                                {% for course in user.course.all %}
                                <p class="mb-1" style="font-size: 20px;">{{ course.title }}
                                    lectures/homeworks</p>
                                <div class="progress rounded mb-3" style="height: 20px;">
                                    <div
                                            {% if course.id|width == 100 %}
                                            class="progress-bar bg-success"
                                            {% endif %}
                                            class="progress-bar" role="progressbar"
                                            style="width: {{ course.id|width }}%"
                                    >{{ course.id|width }}%
                                    </div>
                                </div>
                                <div class="progress rounded mb-3" style="height: 20px;">
                                    <div
                                            {% if course.id|avg == 100 %}
                                            class="progress-bar bg-success"
                                            {% elif course.id|avg >= 75 and course.id|avg <= 89 %}
                                        class="progress-bar bg-info"
                                        {% elif course.id|avg >= 60 and course.id|avg <= 74 %}
                                        class="progress-bar bg-warning"
                                        {% elif course.id|avg < 60 %}
                                        class="progress-bar bg-danger"
                                        {% endif %}
                                        class="progress-bar" role="progressbar"
                                        style="width: {{ course.id|avg }}%"
                                        >{{ course.id|avg|floatformat:2 }}%
                                    </div>
                                </div>
                                {% endfor %}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}